name: Branch workflow
on: 
  push:
    branches-ignore:
      - master
  pull_request:
env:
  DOTNET_CLI_TELEMETRY_OPTOUT: true  
  MSBUILDSINGLELOADCONTEXT: 1
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build solution
      run: dotnet build -c Release
    - name: Create NuGet packages
      run: dotnet pack -c Release --no-build -o nupkg 
    - name: Upload nuget packages
      uses: actions/upload-artifact@v1
      with:
        name: nupkg
        path: nupkg